### ISSUE TITLE
Añadir campo fecha aviso Vigilante tecnológico

### ISSUE THREAD

**Issue by mjtenmat** [mjtenmat/ATHENA#11]
Cuando seleccionamos la opción para visualizar los avisos generados por el vigilante tecnológico, debemos incorporar el campo fecha que nos mostrará la información del dd/mm/aaaa en el que se ha generado el aviso. 
Por ejemplo, en el siguiente aviso sobre "Construction works" debajo del tipo de documento (Licitación, Patente, Documento web y/o Documento académico), añadiríamos el campo "Fecha:" e indicaríamos el día en el que se generó el aviso.
file:///home/mjtena/Documentos/Capturas IU/Capturas presentación/aviso vigilante tecnológico

**Comment by mjaque** [comment]
Requiere modificar la base de datos con:
ALTER TABLE `AvisoTecnologiasEmergentes` ADD `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `revisado`;
Los avisos ya registrados aparecerán con la fecha en la que se hizo la modificación de la base de datos.

**Comment by mjtenmat** [comment]
ERROR 1067 (42000): Invalid default value for 'fecha'
No le gusta.

**Comment by mjaque** [comment]
Prueba: ALTER TABLE AvisoTecnologiasEmergentes ADD fecha DATETIME AFTER revisado;

Los avisos actuales aparecerán a null.

**Comment by mjtenmat** [comment]
Gracias, esa query le gusta más.

Pero tengo problemas con el paquete java.time, me da errores, supongo que
es porque mi versión de java no lo soporta. Utilizo otro paquete o
actualizo a java8?

2017-05-24 8:41 GMT+02:00 Miguel Jaque <notifications@github.com>:

**Comment by mjtenmat** [comment]
No, espera, mi versión de java es 1.8.0_45, ¿debería funcionar java.time,
no? Pues no sé, pero es lo único que genera errores en los ficheros
modificados para ver la fecha en los avisos de tendencia.

**Comment by mjaque** [comment]
Copia el error que te da para ver qué es.

**Comment by mjtenmat** [comment]
Al lanzar Delphos.java
Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 
	The method toDateTime() is undefined for the type Timestamp

	at delphos.iu.PanelAvisosTecnologia.cargarAvisos(PanelAvisosTecnologia.java:92)
	at delphos.iu.PanelAvisosTecnologia.<init>(PanelAvisosTecnologia.java:55)
	at delphos.iu.DelphosFrame.crearPaneles(DelphosFrame.java:96)
	at delphos.iu.DelphosFrame.<init>(DelphosFrame.java:62)
	at delphos.iu.Delphos.run(Delphos.java:42)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by mjtenmat** [comment]
Espera, que probando había cambiado "java.time.LocalDate" por "java.util.Date". Si lo dejo como estaba el error es este:

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Date
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getDeclaredMethods(Class.java:1860)
	at org.hibernate.annotations.common.reflection.java.JavaXClass.getDeclaredMethodProperties(JavaXClass.java:112)
	at org.hibernate.annotations.common.reflection.java.JavaXClass.getDeclaredProperties(JavaXClass.java:129)
	at org.hibernate.annotations.common.reflection.java.JavaXClass.getDeclaredProperties(JavaXClass.java:121)
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:263)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:224)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:775)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processAnnotatedClassesQueue(Configuration.java:3788)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3742)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1410)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1844)
	at delphos.iu.Delphos.crearSesion(Delphos.java:93)
	at delphos.iu.Delphos.getSession(Delphos.java:62)
	at delphos.iu.DelphosFrame.<init>(DelphosFrame.java:59)
	at delphos.iu.Delphos.run(Delphos.java:42)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: Date
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 31 more

**Comment by mjaque** [comment]
Corregida configuración del proyecto a Java 1.8

**Comment by mjtenmat** [comment]
Los nuevos avisos siguen sin insertar fecha en la base de datos, por lo que se ponen a null y producen una excepción en PanelAvisosTendencias.java (línea 92).

**Comment by mjaque** [comment]
Solucionado. Al no poder poner el valor por defecto en la base de datos había que ponerlo por código.
