### ISSUE TITLE
Urgente: Error al arrancar Delphos.java

### ISSUE THREAD

**Issue by mjtenmat** [mjtenmat/ATHENA#15]
He estado editando y eliminando avisos de tendencias, y al intentar arranacar Delphos de nuevo, me da este error. 

Exception in thread "AWT-EventQueue-0" org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [delphos.Tendencia#31]
	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:253)
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:262)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)
	at delphos.Tendencia_$$_jvste33_10.getTerminoPrincipal(Tendencia_$$_jvste33_10.java)
	at delphos.iu.PanelAvisosTendencia$1.compare(PanelAvisosTendencia.java:67)
	at delphos.iu.PanelAvisosTendencia$1.compare(PanelAvisosTendencia.java:1)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at delphos.iu.PanelAvisosTendencia.cargarAvisos(PanelAvisosTendencia.java:71)
	at delphos.iu.PanelAvisosTendencia.<init>(PanelAvisosTendencia.java:56)
	at delphos.iu.DelphosFrame.crearPaneles(DelphosFrame.java:100)
	at delphos.iu.DelphosFrame.<init>(DelphosFrame.java:62)
	at delphos.iu.Delphos.run(Delphos.java:42)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mjtenmat** [comment]
No elimina los registros de avisos en la la base de datos, creo que solo borra el contenido de la columna terminoPrincipal de la tabla Tendencia y por eso se genera el error.
Voy a intentar solucionarlo, si tengo problemas te aviso. ;)

**Comment by mjaque** [comment]
El error indica que se ha borrado la Tendencia 31 y ahora hay una inconsistencia en la base de datos. Posiblemente porque alguna tabla sigue haciendo referencia a la tendencia 31. Pueden ser AvisoTendencia, Tendencia_Documento_Clasificación, Tendencia_Licitacion_Localizacion, Tendencia_Licitación_Sector, etc.

Si el borrado lo has hecho con la aplicación, entonces es que me he olvidado de borrar en alguna tabla.
Si el borrado lo has hecho "a mano", entonces... mal hecho.

¿Cómo lo has hecho?

En cualquier caso, localiza la entrada de las tablas de relación de Tendencia que tenga idTendencia = 31 y bórrala.

**Comment by mjtenmat** [comment]
Ay, hombre de poca fé! Lo eliminé con Delphos, por eso puse edité el error. Lo soluciné, temporalmente, para poder acceder a la aplicación eliminando el aviso con id=31. 
Pero el error lo produce algo que nos hemos dejado en el panel editor de avisos de tendencias, que no borra el registro completo de aviso.
A lo que me refefería cuando decía que iba a intentar solucionarlo, era en el propio código (aquí pequé yo de exceso de fé), pero a la hora de la verdad no me he atrevido a tocarlo. jijijij
