### ISSUE TITLE
tendencias licitación

### ISSUE THREAD

**Issue by mjtenmat** [mjtenmat/ATHENA#8]
Consulta:
Licitación: "solar energy". 01-abr-2000 al 18-abr-2017.

Parámetros POST: action=search&Rs.gp.9719123.pid=home&lgId=en&Rs.gp.9719124.pid=releaseCalendar&quickSearchCriteria=&Rs.gp.9719127.pid=secured&expertSearchCriteria.searchScope=ARCHIVE&expertSearchCriteria.query=PD=[20110401 <> 20120401] AND TD=[3 or 7]&_expertSearchCriteria.statisticsMode=on
Poniendo parámetros de POST: action=search&Rs.gp.9719123.pid=home&lgId=en&Rs.gp.9719124.pid=releaseCalendar&quickSearchCriteria=&Rs.gp.9719127.pid=secured&expertSearchCriteria.searchScope=ARCHIVE&expertSearchCriteria.query=PD=[20110401 <> 20120401] AND TD=[3 or 7]&_expertSearchCriteria.statisticsMode=on
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at delphos.Searcher.verPagina(Searcher.java:1670)
	at delphos.Searcher.verNumLicitacionesModoExperto(Searcher.java:2195)
	at delphos.Searcher.buscarTendencia(Searcher.java:2049)
	at delphos.iu.PanelTendencias.construirDatos(PanelTendencias.java:246)
	at delphos.iu.PanelTendencias.mostrarGraficaTendencia(PanelTendencias.java:213)
	at delphos.iu.PanelTendenciasBuscador.actionPerformed(PanelTendenciasBuscador.java:450)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by mjaque** [comment]
No lo he reproducido. Quizás se haya solucionado con los últimos cambios. Pero no ha devuelto ningún resultado
![bug8](https://cloud.githubusercontent.com/assets/10872229/25583329/a09f4cde-2e91-11e7-96ba-14aa8bb6c12c.png)

**Comment by mjtenmat** [comment]
Pues esta tarde veo de nuevo si se reproduce el error, pero de todos modos, no es posible que devuelva 0 resultados, desde el 1 de abril del 2000 hasta el 18 de abril del 2017 en una búsqueda en TED encontramos 32,766 licitaciones para la búsqueda: solar energy.
![image](https://cloud.githubusercontent.com/assets/24544735/25611848/e30c908a-2f28-11e7-820f-7fd1fded303e.png)

**Comment by mjaque** [comment]
Creo que algo ha cambiado en TED. Pero no he podido comprobarlo porque "me han baneado". En un rato vuelvo.

**Comment by mjtenmat** [comment]
¡Hola Miguel!
Esa misma búsqueda en "vigilancia" la hace correctamente, sigue conectando
bien con TED y devuelve los mismos resultados que el buscador de la web. El
problema nos lo da en "tendencias".

Disculpadme por no haberme pasado a pagar el recibo de abril aún, no he
podido en toda la semana, todas las tardes se me ha hecho tarde para
acercarme. Si queréis puedo hacer una transferencia, o me paso la sema que
viene sin falta, como os venga mejor.

¡Un abrazo!

2017-05-04 11:27 GMT+02:00 Miguel Jaque <notifications@github.com>:

**Comment by mjtenmat** [comment]
Crear un nuevo método para obtener numero de artículos encontrados tras una consulta para poder crear las estadísticas de tendencias.

**Comment by mjaque** [comment]
Creo que ya está.
![solar_energy](https://cloud.githubusercontent.com/assets/10872229/25889185/2c230a10-3569-11e7-8cf8-da9a65a72c7d.png)
Al parecer han cambiado la página de resultados de TED y ahora hay que leer el número de páginas de resultado de otra forma... yo he probado un par de veces y funciona, pero no me cuadra con el error que teníamos antes. Pero como funciona, de momento, lo cierro.

**Comment by mjtenmat** [comment]
Perfecto.

2017-05-10 10:13 GMT+02:00 Miguel Jaque <notifications@github.com>:

**Comment by mjtenmat** [comment]
La búsquedas de tendencias de licitaciones deben permitir consultas estructuradas como "solar energy", o ("solar energy" AND "solar panel"). Antes lo hacían, ahora las hemos perdido.
Tampoco funcionan las búsquedas si filtramos por sectores. Ni las búsquedas solo por sectores, sin términos libres de búsqueda. Algo que también hacían antes.
