### ISSUE TITLE
Análisis tendencias patentes

### ISSUE THREAD

**Issue by mjtenmat** [mjtenmat/ATHENA#9]
Consulta: "solar energy" 18-feb-2017 a 18-abr-2017.
Análisis intervalo.

Patente [id=null, titulo=null, inventor=null, solicitante=null, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205671100U&KC=U, fechaPublicacion=null, resumen=null, cpi=[], documentIdType=docdb, docNumber=205671100, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205671857.U/biblio
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'A47D7/00%' ORDER BY codigo LIMIT 1
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'A47D15/00%' ORDER BY codigo LIMIT 1
ListaCPI: A47D 7/ 00 A I - Children's beds (beds in general A47C), A47D 15/ 00 A I - Accessories for children's furniture, e.g. safety belts, baby-bottle holders (holders for bottles for medicinal feeding A61J 9060000; safety belts or body harnesses, in general A62B 35000000; safety belts or body harnesses in land vehicles B60R 22000000; harnessing in aircraft B64D 25060000)
Patente [id=null, titulo=种新型婴儿床, Novel baby bed, inventor=LIU FANGYI, LIU FANGYI, solicitante=ANHUI BUSINESS COLLEGE, ANHUI BUSINESS COLLEGE, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205671857U&KC=U, fechaPublicacion=Wed Nov 09 00:00:00 CET 2016, resumen=本实用新型属于日常生活技术领域且公开了种新型婴儿床，包括竖梁、面板、置物盒和摇床，所述竖梁侧面板上连接有摄像头、甲醛检测仪和太阳能电池板，所述竖梁底部设有万向刹车滚轮，所述面板表层设有LED声控感应灯，所述面板内侧设有蓄电池、蓝牙音乐播放器和烟雾报警器。本实用新型通过摄像头的设置记录宝宝成长历程，通过太阳能电池板的设置可以将太阳能转化为电能为蓄电池充电，通过甲醛检测仪的设置实现对居住环境监测，通过烟雾报警器的设置起到预警作用，由于蓝牙音乐播放器的设置实现音乐播放，吸引宝宝注意力，给宝宝音乐享受，通过LED声控感应灯的设置实现夜间照明，方便照看，通过摇篮的设置使功能更全，实用性强，值得推广。The utility model belongs to the technical field of daily life and a novel baby bed is disclosed, including erecting roof beam, panel, putting thing box and shaking table, be connected with camera, formaldehyde detector and solar cell panel on the panel of perpendicular roof beam one side, it is equipped with universal brake gyro wheel to erect breast portion, the panel top layer is equipped with LED acoustic control response lamp, the panel inboard is equipped with battery, bluetooth audio player and smoke alarm. The utility model discloses a camera set up the record baby coarse that grows up, can be storage battery charging for the electric energy with solar energy transformation through setting up of solar cell panel, the realization that sets up through the formaldehyde detector is monitored the living environment, early warning function is played in setting through smoke alarm, because setting up of bluetooth audio player realizes the music broadcast, attract baby's attention, enjoy for baby's music, realize the illumination at night through setting up of LED acoustic control response lamp, conveniently look after, make the function more complete through setting up of cradle, therefore, the clothes hanger is strong in practicability, and is worthy of popularization., cpi=[], documentIdType=docdb, docNumber=205671857, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205672151.U/biblio
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205672151.U/biblio
	at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at delphos.Searcher.completarPatente(Searcher.java:1073)
	at delphos.Searcher.buscarPatentesEnLinea(Searcher.java:1017)
	at delphos.Searcher.buscarTodasPatentesEnLinea(Searcher.java:2653)
	at delphos.Searcher.analizarTendenciaPeriodo(Searcher.java:2610)
	at delphos.Searcher.analizarTendencia(Searcher.java:2535)
	at delphos.iu.JFrameAnalisisTendencias.<init>(JFrameAnalisisTendencias.java:55)
	at delphos.iu.FrameGraficoTendencia$2.actionPerformed(FrameGraficoTendencia.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205672151.U/biblio
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at delphos.Searcher.completarPatente(Searcher.java:1068)
	... 42 more
Patente [id=null, titulo=null, inventor=null, solicitante=null, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205672151U&KC=U, fechaPublicacion=null, resumen=null, cpi=[], documentIdType=docdb, docNumber=205672151, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205680372.U/biblio
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'G09F9/33%' ORDER BY codigo LIMIT 1
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'H02J7/35%' ORDER BY codigo LIMIT 1
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'H05K7/20%' ORDER BY codigo LIMIT 1
ListaCPI: G09F 9/ 33 A I - … being semiconductor devices, e.g. diodes, H02J 7/ 35 A I - … with light sensitive cells, H05K 7/ 20 A I - Modifications to facilitate cooling, ventilating, or heating
Patente [id=null, titulo=种室外节能的LED显示箱, LED display box of outdoor energy -conservation, inventor=GU KAI, GU KAI, solicitante=GU KAI, GU KAI, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205680372U&KC=U, fechaPublicacion=Wed Nov 09 00:00:00 CET 2016, resumen=本实用新型涉及显示器技术领域。本实用新型种室外节能的LED显示箱，包括太阳电池板，所述太阳能电池板安装在高容量蓄电池的上方，且高容量蓄电池安装在箱体的顶部，所述箱体的左右两侧均设置有散热窗，所述箱体上设置有LED显示屏，且箱体的底部设置有安装底板，所述安装底板的下方设置有支撑支柱，所述箱体内设置有控制板，且控制板上设置有充电保护器，所述充电保护器的右侧设置有信号接收器，且充电保护器的下方设置有LED稳控电源开关，所述稳控电源开关的右侧设置有中央处理器。本实用新型通过在显示箱顶部设置的太阳能电池板可以吸收太阳能转化为电能储存在高容量蓄电池内，提供LED显示箱内的设备用电，节省电力资源达到节能减排的效果。The utility model relates to a display technical field. The utility model relates to a LED display box of outdoor energy -conservation, including solar cell panel, solar cell panel installs in the top of high power capacity battery, and the high power capacity battery installs at the top of box, the left and right sides of box all is provided with the heat dissipation window, be provided with the LED display screen on the box, and the bottom of box is provided with mounting plate, mounting plate's below is provided with the support pillar, be provided with the control panel in the box, and be provided with the charge protection ware on the control panel, the right side of charge protection ware is provided with signal receiver, and the below of charge protection ware is provided with LED and surely controls switch, the right side of surely controlling switch is provided with central processing unit. The utility model discloses a can absorb solar energy transformation at the solar cell panel of display box top setting and store in the high power capacity battery for the electric energy, provide the equipment power consumption in the LED display box, save the effect that the electric power resource reaches energy saving and emission reduction., cpi=[], documentIdType=docdb, docNumber=205680372, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205681670.U/biblio
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205681670.U/biblio
	at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at delphos.Searcher.completarPatente(Searcher.java:1073)
	at delphos.Searcher.buscarPatentesEnLinea(Searcher.java:1017)
	at delphos.Searcher.buscarTodasPatentesEnLinea(Searcher.java:2653)
	at delphos.Searcher.analizarTendenciaPeriodo(Searcher.java:2610)
	at delphos.Searcher.analizarTendencia(Searcher.java:2535)
	at delphos.iu.JFrameAnalisisTendencias.<init>(JFrameAnalisisTendencias.java:55)
	at delphos.iu.FrameGraficoTendencia$2.actionPerformed(FrameGraficoTendencia.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205681670.U/biblio
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at delphos.Searcher.completarPatente(Searcher.java:1068)
	... 42 more
Patente [id=null, titulo=null, inventor=null, solicitante=null, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205681670U&KC=U, fechaPublicacion=null, resumen=null, cpi=[], documentIdType=docdb, docNumber=205681670, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205671651.U/biblio
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205671651.U/biblio
	at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at delphos.Searcher.completarPatente(Searcher.java:1073)
	at delphos.Searcher.buscarPatentesEnLinea(Searcher.java:1017)
	at delphos.Searcher.buscarTodasPatentesEnLinea(Searcher.java:2653)
	at delphos.Searcher.analizarTendenciaPeriodo(Searcher.java:2610)
	at delphos.Searcher.analizarTendencia(Searcher.java:2535)
	at delphos.iu.JFrameAnalisisTendencias.<init>(JFrameAnalisisTendencias.java:55)
	at delphos.iu.FrameGraficoTendencia$2.actionPerformed(FrameGraficoTendencia.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
Patente [id=null, titulo=null, inventor=null, solicitante=null, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205671651U&KC=U, fechaPublicacion=null, resumen=null, cpi=[], documentIdType=docdb, docNumber=205671651, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205676241.U/biblio
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205671651.U/biblio
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at delphos.Searcher.completarPatente(Searcher.java:1068)
	... 42 more
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205676241.U/biblio
Patente [id=null, titulo=null, inventor=null, solicitante=null, localizacion=CN, url=http://worldwide.espacenet.com/publicationDetails/biblio?DB=worldwide.espacenet.com&II=0&ND=3&adjacent=true&locale=en_EP&FT=D&CC=CN&NR=205676241U&KC=U, fechaPublicacion=null, resumen=null, cpi=[], documentIdType=docdb, docNumber=205676241, kind=U]
URI patente: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205676792.U/biblio
	at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at delphos.Searcher.completarPatente(Searcher.java:1073)
	at delphos.Searcher.buscarPatentesEnLinea(Searcher.java:1017)
	at delphos.Searcher.buscarTodasPatentesEnLinea(Searcher.java:2653)
	at delphos.Searcher.analizarTendenciaPeriodo(Searcher.java:2610)
	at delphos.Searcher.analizarTendencia(Searcher.java:2535)
	at delphos.iu.JFrameAnalisisTendencias.<init>(JFrameAnalisisTendencias.java:55)
	at delphos.iu.FrameGraficoTendencia$2.actionPerformed(FrameGraficoTendencia.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ops.epo.org/3.1/rest-services/published-data/publication/docdb/CN.205676241.U/biblio
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at delphos.Searcher.completarPatente(Searcher.java:1068)
	... 42 more
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'E01F9/608%' ORDER BY codigo LIMIT 1
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'E01F9/615%' ORDER BY codigo LIMIT 1
Hibernate: SELECT descripcion FROM CPI_Oficial WHERE codigo LIKE 'E01F9/619%' ORDER BY codigo LIMIT 1

**Comment by mjaque** [comment]
No lo he reproducido. Puede que se haya solucionado con los cambios que he hecho.
![bug9](https://cloud.githubusercontent.com/assets/10872229/25583192/0efe5d88-2e91-11e7-8b49-4d8e915881a3.png)
